name: SPrefix
version: 1.0.0
api: [3.0.0, 3.1.0, 4.0.0]
author: solo
main: solo\sprefix\SPrefix
permissions:
  sprefix:
    default: op
    children:
      sprefix.command:
        default: op
        children:
          sprefix.command.defaultprefix:
            default: op
          sprefix.command.pluginprefix:
            default: op
